
module.exports = JSON.parse(
    `{
        "nodes":[
            {"uuid":1,"lat":0,"lon":0,"ele":0},
            {"uuid":2,"lat":1,"lon":1,"ele":5},
            {"uuid":3,"lat":0,"lon":2,"ele":10},
            {"uuid":4,"lat":0,"lon":3,"ele":13},
            {"uuid":5,"lat":1,"lon":3,"ele":0},
            {"uuid":6,"lat":2,"lon":4,"ele":-3},
            {"uuid":7,"lat":2,"lon":2,"ele":-5},
            {"uuid":8,"lat":4,"lon":1,"ele":6},
            {"uuid":9,"lat":5,"lon":2,"ele":8},
            {"uuid":10,"lat":5,"lon":5,"ele":15}
        ],
        "edges":[
            {"a":1,"b":2},
            {"a":1,"b":3},
            {"a":2,"b":3},
            {"a":2,"b":7},
            {"a":2,"b":8},
            {"a":3,"b":4},
            {"a":4,"b":5},
            {"a":5,"b":6},
            {"a":5,"b":7},
            {"a":6,"b":7},
            {"a":7,"b":10},
            {"a":8,"b":9},
            {"a":9,"b":10}
        ]
    }`
);